services:
  oauth2-proxy:
    build:
      context: ./oauth2-proxy
    environment:
    - FORWARD_HOST=echo-server
    - FORWARD_PORT=80
    - NGINX_PORT=8080
    - OIDC_REDIRECT_URI_PATH=/redirect_uri
    - OIDC_ACCEPT_NONE_ALG=true
    - OIDC_DISCOVERY=http://host.docker.internal:3333/auth/realms/myrealm/.well-known/openid-configuration
    - OIDC_CLIENT_ID=nginx2
    - OIDC_CLIENT_SECRET=a9d487b6-587d-4577-a47f-7e505cce5dab
    - OIDC_REDIRECT_URI_SCHEME=http
    - OIDC_LOGOUT_PATH=/logout
    - OIDC_REDIRECT_AFTER_LOGOUT_URI=http://host.docker.internal:3333/auth/realms/myrealm/protocol/openid-connect/logout?redirect_uri=http://localhost/


    ports:
      - 8080:8080    

  echo-server:
    image: ealen/echo-server:0.9.2
    ports:
      - 3000:80