services:
  nginx-proxy-basic-auth:
    build:
      context: ./nginx-proxy
    environment:
    - FORWARD_HOST=echo-server
    - FORWARD_PORT=80
    - BASIC_AUTH_USERNAME=admin
    - BASIC_AUTH_PASSWORD=admin
    - NGINX_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/../html:/usr/share/nginx/html

  echo-server:
    image: ealen/echo-server:0.9.2
    ports:
      - 3000:80